- docs/index.md
- docs/introduction.md
- docs/introduction/basic_usage.md
- docs/pipeline/adapters.md
- docs/pipeline/fetchers.md
- docs/pipeline/parsers.md
- docs/pipeline/pipeline.md
- mkdocs.yml
- poetry.lock
- pyproject.toml
- Add docs generated by docstrings
> feat: add docs generated from docstrings

- docs/changelog.md
- docs/index.md
- docs/introduction/basic_usage.md
- docs/models/metadata.md
- docs/models/metadata_processing_error.md
- docs/models/token.md
- docs/pipeline/adapters.md
- docs/pipeline/fetchers.md
- docs/pipeline/parsers.md
- docs/pipeline/pipeline.md
- docs/usage.md
- mkdocs.yml
- offchain/metadata/parsers/collection/ens.py
- offchain/metadata/pipelines/metadata_pipeline.py
> feat: More docs

- offchain/metadata/pipelines/metadata_pipeline.py
- tests/metadata/pipelines/test_metadata_pipeline.py
- Fetcher token uri if it is not passed in
> feat: fetch token uri if not passed in

- docs/changelog.md
- docs/contributing.md
- docs/index.md
- docs/usage.md
- offchain/metadata/models/token.py
- offchain/metadata/parsers/collection/collection_parser.py
- offchain/metadata/parsers/schema/schema_parser.py
- offchain/metadata/pipelines/metadata_pipeline.py
- tests/metadata/pipelines/test_metadata_pipeline.py
- Add usage docs
- Wrap token uri fetching in a try/catch
> feat: Add more usage docs 

- docs/index.md
- docs/usage.md
- offchain/metadata/adapters/arweave.py
- offchain/metadata/adapters/base_adapter.py
- offchain/metadata/adapters/data_uri.py
- offchain/metadata/adapters/ipfs.py
- offchain/metadata/fetchers/metadata_fetcher.py
- offchain/metadata/models/metadata.py
- offchain/metadata/models/metadata_processing_error.py
- offchain/metadata/models/token.py
- offchain/metadata/parsers/collection/collection_parser.py
- offchain/metadata/parsers/schema/schema_parser.py
- offchain/metadata/pipelines/metadata_pipeline.py
- add more docstrings for better documentation
> feat: add more docstrings for better documentation

- docs/contributing/guidelines.md
- docs/usage.md
- mkdocs.yml
- offchain/__init__.py
- Add a `tutorial` page for contributing docs
> feat: add scaffold for contributing docs

- offchain/__init__.py
`__init__.py` is needed in all directories if one is present in the root
> Add missing `__init__.py`s

- poetry.lock
- pyproject.toml
> Pyproject updates

- pyproject.toml
> change authors field to zora eng

- docs/contributing/metadata_tutorial.md
- docs/usage/overview.md
> Doc updates

- docs/contributing/metadata_tutorial.md
- Improve metadata contribution tutorial
> feat: improve metadata contribution tutorial

- docs/changelog.md
- offchain/__init__.py
- offchain/metadata/__init__.py
- offchain/metadata/adapters/__init__.py
- offchain/metadata/adapters/base_adapter.py
- offchain/metadata/get_token_metadata.py
- offchain/metadata/models/token.py
- offchain/metadata/pipelines/__init__.py
- offchain/metadata/pipelines/metadata_pipeline.py
- pyproject.toml
- tests/metadata/models/test_token.py
- tests/metadata/test_get_token_metadata.py
- add a `get_token_metadata()` function for simple use cases
- add basic validation logic for `chain_identifier` field on `Token`
- expose `get_token_metadata`, `Metadata`, `MetadataFetcher`, `MetadataPipeline`, `MetadataProcessingError`, and `Token` as root-level imports
> feat: Minor package improvements (imports, validation, and ease of use)

- docs/contributing/metadata_tutorial.md
- docs/index.md
- docs/usage/customize.md
- docs/usage/overview.md
> feat: minor improvements for docs

- docs/changelog.md
- docs/index.md
- offchain/metadata/models/metadata_processing_error.py
- pyproject.toml
- tests/metadata/models/test_metadata_processing_error.py
- tests/metadata/pipelines/test_metadata_pipeline.py
- bug fix: a typo resulted in `token` field being assigned to the model class, rather than being specified as a type annotation
- add regression tests
> fix: patch fix typo that caused token field to be assigned to class instead of object

- docs/changelog.md
- docs/index.md
- offchain/metadata/parsers/schema/opensea.py
- pyproject.toml
- tests/metadata/parsers/test_opensea_parser.py
- bug fix: add a type check to `should_parse_token()` in `OpenseaParser` to validate that `raw_data` is a `dict`
> fix: patch fix opensea parser should_parser_token function

- docs/contributing/publish_release.md
- mkdocs.yml
> Documentation for publishing releases

- offchain/web3/contract_caller.py
- tests/metadata/web3/test_async_batching.py
> Create Async Contract Caller

- docs/changelog.md
- docs/index.md
- pyproject.toml
> BACK-1720: bump version to v0.2.5

- docs/changelog.md
- docs/index.md
- pyproject.toml
> BACK-1791: release notes v0.2.6

- docs/changelog.md
- docs/index.md
- offchain/metadata/parsers/catchall/default_catchall.py
- offchain/metadata/parsers/collection/artblocks.py
- offchain/metadata/parsers/collection/ens.py
- offchain/metadata/parsers/schema/opensea.py
- pyproject.toml
- tests/metadata/parsers/test_default_catchall_parser.py
- tests/metadata/parsers/test_opensea_parser.py
> BACK-2749: support svg image uri in opensea parser
